version: '3' 
networks:
  net:
services:
  blog-api:
    image: blog-api # Blog API (Spring)
    container_name: blog-api
    ports:
      - 8081:8080
    networks:
      - net
    depends_on:
#      - search-api
      - auth-api
#    environment:
# not used yet     - JVM_OPTS=-Xmx150M -Xms150M -XX:MaxPermSize=100M
#      - CATALINA_OPTS=-Xmx150M -Xms50M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          #cpus: '0.001'
          memory: 50M
        #reservations:
        #  cpus: '0.0001'
        #  memory: 20M
  auth-api: # Authentication API (Spring)
    image: auth-api
    container_name: auth-api
    ports:
      - 8083:8080
    networks:
      - net
#  search-api: # Search API (Spark)
#    image: search-api
#    container_name: search-api 
#    ports:
#      - 4567:4567
#    networks:
#      - net
#    depends_on: 
#      - solr-master
#  solr-master: # Solr master
#    image: solr-master
#    container_name: solr-master
#    ports:
#      - 8983:8983
#    networks:
#      - net
