version: '3' 
networks:
  net:
services:
  blog-api:
    image: blog-api # Blog API (Spring)
    container_name: blog-api
    ports:
      - 8081:8080
    networks:
      - net
    depends_on:
#      - search-api
      - auth-api
      - mysql-database
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
#     - CATALINA_OPTS=-Xmx150M -Xms50M -XX:MaxPermSize=50M
    command: >
      /bin/bash -c "
        while ! nc -z mysql-database 3306;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
      "
    deploy:
      resources:
        limits:
          #cpus: '0.001'
          memory: 50M
        #reservations:
        #  cpus: '0.0001'
        #  memory: 20M
  auth-api: # Authentication API (Spring)
    image: auth-api
    container_name: auth-api
    ports:
      - 8083:8080
    networks:
      - net
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  mysql-database:
    image: mysql-database
    container_name: mysql-database
    ports:
      - 3306:3306
    networks:
      - net

#  search-api: # Search API (Spark)
#    image: search-api
#    container_name: search-api 
#    ports:
#      - 4567:4567
#    networks:
#      - net
#    depends_on: 
#      - solr-master
#  solr-master: # Solr master
#    image: solr-master
#    container_name: solr-master
#    ports:
#      - 8983:8983
#    networks:
#      - net
