version: "3.3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres-scripts:/docker-entrypoint-initdb.d/
      - ./postgres-database-data:/var/lib/
  auth-mock:
    build:
      context: ./json-server-mock
      dockerfile: Dockerfile
    command: node index.js
    environment:
      - PORT=8083
    ports:
      - 8083:8083
  # search-api: 
  #   image: search-api
  #   container_name: search-api
  #   ports:
  #     - 4567:4567
  #   networks:
  #     - net
  #   depends_on: 
  #     - solr-master
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  # solr-master: 
  #   image: solr-master
  #   container_name: solr-master
  #   ports:
  #     - 8983:8983
  #   networks:
  #     - net
  #   environment:
  #     - BLOG_MYSQL_URL=jdbc:mysql://mysql-database:3306/blogdb?useSSL=false
  #     - BLOG_MYSQL_USERNAME=root
  #     - BLOG_MYSQL_PASSWORD=root
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M    
networks:
  default:
    external:
      name: net