server:
  port: 8081
spring:
  datasource:
    plataform: postgres
    url: ${BLOG_DB_URL:jdbc:postgresql://127.0.0.1:5432/blogdb}
    username: ${BLOG_DB_USERNAME:postgres}
    password: ${BLOG_DB_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:/db/base,classpath:/db/testdata,classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
blog:
  posts:
    page-size: 6
    top-list:
      page-size: 10
urls:
  auth:
    check-token: http://127.0.0.1:8083/token/check
    get-token: http://127.0.0.1:8083/token
  search: http://127.0.0.1:4567/search
