blog:
  posts:
    page-size: 6
    top-list:
      page-size: 10
blog-api:
  password: ${BLOG_API_PASSWORD}
  username: ${BLOG_API_USERNAME}
spring:
  datasource:
    plataform: postgres
    url: ${BLOG_DB_URL}
    username: ${BLOG_DB_USERNAME}
    password: ${BLOG_DB_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
  flyway:
    enabled: true
    locations: classpath:/db/base,classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
urls:
  auth:
    check-token: http://apps-server:8080/auth-api/token/check
    get-token: http://apps-server:8080/auth-api/token
  search: http://search-api:4567/search
  
blog-api:
  username: ${BLOG_SERVICE_USERNAME}
  password: ${BLOG_SERVICE_PASSWORD}
