blog:
  posts:
    page-size: 1
    top-list:
      page-size: 10
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
urls:
  auth:
    check-token: http://auth-api:8080/auth-api/auth/checkToken
    get-token: http://auth-api:8080/auth-api/auth/login
  search: 'http://search-api:4567/search '
  
blog-api:
  username: ${BLOG_SERVICE_USERNAME:BLOG}
  password: ${BLOG_SERVICE_PASSWORD:123456}
