server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:/db/base,classpath:/db/testdata,classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
blog:
  posts:
    page-size: 6
    top-list:
      page-size: 10
blog-db:
  password: root
  url: jdbc:mysql://127.0.0.1:3306/blogdb?useSSL=false
  username: root
urls:
  auth:
    check-token: http://127.0.0.1:8083/api/token/check
    get-token: http://127.0.0.1:8083/api/token/create
  search: http://127.0.0.1:4567/search
