spring:
  application:
    name: blog-api
  datasource:
    tomcat:
      max-wait: 100000
  flyway:
    baseline-on-migrate: true
    clean-on-validation-error: true
  profiles:
    active: '@activeProfile@'
  boot:
    admin:
      client:
        url: http://localhost:8090  
management:
  endpoints:
    web:
      exposure:
        include: '*'
